name: Study github actions context

on: push

jobs:
  define-outputs:
    name: define-outputs
    runs-on: ubuntu-latest
    steps:
      - name: Check if dev
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "this is dev."
          
      - name: Check if stg
        if: ${{ startsWith(github.ref_name, 'release') }}
        run: |
          echo "this is stg."
